### ISSUE TITLE
Example 12 cannot find ShellFileSystem

### ISSUE THREAD

**Issue by markfirmware** [markfirmware/ultibodocker#18]
Now reviewing build log to see if there were any errors building rtl.

**Comment by ultibohub** [comment]
Try using ShellFilesystem instead of ShellFileSystem in the uses clause. We accidentally made the file names of the units in the extras folder case sensitive without thinking about the Linux use case.

**Comment by markfirmware** [comment]
That fixed it. I am using a branch of my fork until it is changed upstream. Thanks.

**Comment by markfirmware** [comment]
Fixed up stream. Thanks!
